// Generated by scripts/generate-model-provenance.py; do not edit.
import Foundation

struct GeneratedWhisperModel: Sendable {
    let id: String
    let displayName: String
    let filename: String
    let sha256: String
    let sizeBytes: Int64
    let license: String?
    let languages: [String]?
    let revision: String
    let source: String
}

struct GeneratedParakeetManifestEntry: Codable, Hashable, Sendable {
    let path: String
    let size: Int64
    let sha256: String
    let component: String
    let role: String

    init(path: String, size: Int64, sha256: String, component: String = "Unknown", role: String = "unknown") {
        self.path = path
        self.size = size
        self.sha256 = sha256
        self.component = component
        self.role = role
    }
}

enum GeneratedModelProvenance {
    static let whisperRepository = "ggerganov/whisper.cpp"
    static let whisperRevision = "5359861c739e955e79d9a303bcbc70fb988958b1"
    static let parakeetRepository = "FluidInference/parakeet-tdt-0.6b-v3-coreml"
    static let parakeetRevision = "aed02740059203c4a87495924f685de3722ae9ce"
    static let fluidAudioRevision = "19600a485baa4998812e4654b70d2bab8f2c9949"

    static let whisper: [GeneratedWhisperModel] = [
        .init(id: "whisper-tiny-q5_1", displayName: "Tiny (Q5_1) - 32MB", filename: "ggml-tiny-q5_1.bin", sha256: "818710568da3ca15689e31a743197b520007872ff9576237bda97bd1b469c3d7", sizeBytes: 32152673, license: "MIT", languages: ["multilingual"], revision: whisperRevision, source: whisperRepository),
        .init(id: "whisper-base-q5_1", displayName: "Base (Q5_1) - 60MB", filename: "ggml-base-q5_1.bin", sha256: "422f1ae452ade6f30a004d7e5c6a43195e4433bc370bf23fac9cc591f01a8898", sizeBytes: 59707625, license: "MIT", languages: ["multilingual"], revision: whisperRevision, source: whisperRepository),
        .init(id: "whisper-small-q5_1", displayName: "Small (Q5_1) - 190MB", filename: "ggml-small-q5_1.bin", sha256: "ae85e4a935d7a567bd102fe55afc16bb595bdb618e11b2fc7591bc08120411bb", sizeBytes: 190085487, license: "MIT", languages: ["multilingual"], revision: whisperRevision, source: whisperRepository),
        .init(id: "whisper-medium-q5_0", displayName: "Medium (Q5_0) - 539MB", filename: "ggml-medium-q5_0.bin", sha256: "19fea4b380c3a618ec4723c3eef2eb785ffba0d0538cf43f8f235e7b3b34220f", sizeBytes: 539212467, license: "MIT", languages: ["multilingual"], revision: whisperRevision, source: whisperRepository),
        .init(id: "whisper-large-v3-turbo-q5_0", displayName: "Large v3 Turbo (Q5_0) - 574MB", filename: "ggml-large-v3-turbo-q5_0.bin", sha256: "394221709cd5ad1f40c46e6031ca61bce88931e6e088c188294c6d5a55ffa7e2", sizeBytes: 574041195, license: "MIT", languages: ["multilingual"], revision: whisperRevision, source: whisperRepository),
    ]

    static let parakeetCompiled: [GeneratedParakeetManifestEntry] = [
        .init(path: "Decoder.mlmodelc/analytics/coremldata.bin", size: 243, sha256: "4238c4e81ecd0dc94bd7dfbb60f7e2cc824107c1ffe0387b8607b72833dba350", component: "Decoder", role: "compiled"),
        .init(path: "Decoder.mlmodelc/coremldata.bin", size: 554, sha256: "18647af085d87bd8f3121c8a9b4d4564c1ede038dab63d295b4e745cf2d7fb99", component: "Decoder", role: "compiled"),
        .init(path: "Decoder.mlmodelc/metadata.json", size: 3427, sha256: "a39e93cd8371b8ded92635c7804fcd0590f0d1dd9415c6d19a0484be073077d9", component: "Decoder", role: "compiled"),
        .init(path: "Decoder.mlmodelc/model.mil", size: 13110, sha256: "ef2a0a281695398a62fde86ac269c68f73d5b578d7ed3b31f2ba91a2d1ea1f35", component: "Decoder", role: "compiled"),
        .init(path: "Decoder.mlmodelc/weights/weight.bin", size: 23604992, sha256: "48adf0f0d47c406c8253d4f7fef967436a39da14f5a65e66d5a4b407be355d41", component: "Decoder", role: "compiled"),
        .init(path: "Encoder.mlmodelc/analytics/coremldata.bin", size: 243, sha256: "42e638870d73f26b332918a3496ce36793fbb413a81cbd3d16ba01328637a105", component: "Encoder", role: "compiled"),
        .init(path: "Encoder.mlmodelc/coremldata.bin", size: 485, sha256: "d48034a167a82e88fc3df64f60af963ab3983538271175b8319e7d5720a0fb86", component: "Encoder", role: "compiled"),
        .init(path: "Encoder.mlmodelc/metadata.json", size: 2921, sha256: "da24da9cca943fb29d7fa8e376d57fca7cb3aa08ca51b956b0b0e56813f087e9", component: "Encoder", role: "compiled"),
        .init(path: "Encoder.mlmodelc/model.mil", size: 959769, sha256: "ed7b19156ca29fa7dfd6891deb9fda4b0e8893f68597c985d135736546a43808", component: "Encoder", role: "compiled"),
        .init(path: "Encoder.mlmodelc/weights/weight.bin", size: 445187200, sha256: "e2020f323703477a5b21d7c2d282c403e371afb5962e79877e3033e73ba6f421", component: "Encoder", role: "compiled"),
        .init(path: "JointDecisionv3.mlmodelc/analytics/coremldata.bin", size: 243, sha256: "26def4bf73dd56d29dee21c8ef97cb8969e62f6120ed1adc91e46828e2737b6c", component: "JointDecisionv3", role: "compiled"),
        .init(path: "JointDecisionv3.mlmodelc/coremldata.bin", size: 521, sha256: "f5fc08b741400f0088492c9e839418b1e18522f19cba28d361dd030c5f398342", component: "JointDecisionv3", role: "compiled"),
        .init(path: "JointDecisionv3.mlmodelc/metadata.json", size: 3453, sha256: "d9307211b9a37e0f0ac260c7660b1571a3de25841035cfdf9b58fd40425f890f", component: "JointDecisionv3", role: "compiled"),
        .init(path: "JointDecisionv3.mlmodelc/model.mil", size: 11775, sha256: "be60732943389a047175111a83f8839f3eb39d4803adafa828a0871b2f39818d", component: "JointDecisionv3", role: "compiled"),
        .init(path: "JointDecisionv3.mlmodelc/weights/weight.bin", size: 12642764, sha256: "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e", component: "JointDecisionv3", role: "compiled"),
        .init(path: "Preprocessor.mlmodelc/analytics/coremldata.bin", size: 243, sha256: "c9beeb989c8d66f8be11df59bc6df277ec76cee404f6865b46243835ef562f6d", component: "Preprocessor", role: "compiled"),
        .init(path: "Preprocessor.mlmodelc/coremldata.bin", size: 486, sha256: "dbde3f2300842c1fd51ef3ff948a0bcffe65ffd2dca10707f2509f32c1d65b1d", component: "Preprocessor", role: "compiled"),
        .init(path: "Preprocessor.mlmodelc/metadata.json", size: 2841, sha256: "2a98699e22d279dd37fa1d238aeb1c6db1df0d6fad687775324157689d8f3acf", component: "Preprocessor", role: "compiled"),
        .init(path: "Preprocessor.mlmodelc/model.mil", size: 28181, sha256: "4b8518a956450fec57f06c2a21bdffc26973f7f1fa6842fb38fe917f896b6b93", component: "Preprocessor", role: "compiled"),
        .init(path: "Preprocessor.mlmodelc/weights/weight.bin", size: 491072, sha256: "129b76e3aeafa8afa3ea76d995b964b145fe83700d579f6ff42c4c38fa0968ea", component: "Preprocessor", role: "compiled"),
        .init(path: "parakeet_vocab.json", size: 151122, sha256: "7ec60e05f1b24480736ec0eed40900f4626bce1fa9a60fd700ec7e2a59198735", component: "Vocabulary", role: "compiled"),
    ]

    // Generated for the inactive in-memory .mlpackage snapshot provider.
    static let parakeetSource: [GeneratedParakeetManifestEntry] = [
        .init(path: "mlpackages/Preprocessor.mlpackage/Data/com.apple.CoreML/model.mlmodel", size: 20454, sha256: "abc41e3d6c4f2d401ca445c85aa4884244eabed9bdec7b4ec7e60d691140cdfb", component: "Preprocessor", role: "specification"),
        .init(path: "mlpackages/Preprocessor.mlpackage/Data/com.apple.CoreML/weights/weight.bin", size: 491072, sha256: "129b76e3aeafa8afa3ea76d995b964b145fe83700d579f6ff42c4c38fa0968ea", component: "Preprocessor", role: "weights"),
        .init(path: "mlpackages/Encoder.mlpackage/Data/com.apple.CoreML/model.mlmodel", size: 661900, sha256: "cfec08b0fb04d25f7f61203e02571091e53d22fc85c47c5cc9699019d2ab0d2a", component: "Encoder", role: "specification"),
        .init(path: "mlpackages/Encoder.mlpackage/Data/com.apple.CoreML/weights/weight.bin", size: 445187200, sha256: "e2020f323703477a5b21d7c2d282c403e371afb5962e79877e3033e73ba6f421", component: "Encoder", role: "weights"),
        .init(path: "mlpackages/Decoder.mlpackage/Data/com.apple.CoreML/model.mlmodel", size: 11672, sha256: "8bfdcef9fb1b46a1ec2f3c1895c74ed90644a69105efda370e412a522bd5b353", component: "Decoder", role: "specification"),
        .init(path: "mlpackages/Decoder.mlpackage/Data/com.apple.CoreML/weights/weight.bin", size: 23604992, sha256: "48adf0f0d47c406c8253d4f7fef967436a39da14f5a65e66d5a4b407be355d41", component: "Decoder", role: "weights"),
        .init(path: "JointDecisionv3.mlpackage/Data/com.apple.CoreML/model.mlmodel", size: 10608, sha256: "c31044bcbcc2959ced2a59e8a0177b617aa359fa1ad613b57de5b63a430f9e31", component: "JointDecisionv3", role: "specification"),
        .init(path: "JointDecisionv3.mlpackage/Data/com.apple.CoreML/weights/weight.bin", size: 12642764, sha256: "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e", component: "JointDecisionv3", role: "weights"),
        .init(path: "parakeet_vocab.json", size: 151122, sha256: "7ec60e05f1b24480736ec0eed40900f4626bce1fa9a60fd700ec7e2a59198735", component: "Vocabulary", role: "vocabulary"),
    ]
    static let canonicalProvenanceSHA256 = "9707fb09598e23902d5a3847e84acae468ca85b357d6c100b199f35a7312e3b2"
}
